
services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    volumes:
      - ./backend/.env.production:/app/.env
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "8081:80"
    environment:
      - VITE_API_URL=http://localhost:8080
    depends_on:
      - backend
    networks:
      - app-network

  jaeger:
    image: jaegertracing/all-in-one:1.48
    ports:
      - "16686:16686" # UI
      - "4318:4318"   # OTLP receiver
    networks:
      - app-network


networks:
  app-network:
    driver: bridge 